name: Build and Deploy a Branch to GH Pages
on: 
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code
        uses: actions/checkout@v3

      - name: Install and Build
        env:
          BASE_URL: /vite-plugin-ssr-svelte/
        run: | 
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          folder: dist/client
          # Remove previous build files
          clean: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
